### ISSUE TITLE
Typos in function names

### ISSUE THREAD

**Issue by LilithWittmann** [demokratie-live/bt-dip-sdk#1]
Thanks for your great work 😊 

I found two small typos in the function names:
getD**ur**cksachen -> getDrucksachen
getPlenarprotok**oel**le -> getPlenarprotokolle
![signal-2021-06-13-235852](https://user-images.githubusercontent.com/891030/121823262-708e2a00-cca4-11eb-9e1a-cd9f68c3fc6b.jpeg)

**Comment by ManAnRuck** [comment]
🙈  previously it was not fixed correctly. But with the latest alpha(8) it should work now (incl. TypeSafety)
