### ISSUE TITLE
ApiKey Sicherheitinfo

### ISSUE THREAD

**Issue by ksaadDE** [demokratie-live/bt-dip-sdk#2]
```
const config = new Configuration({
  apiKey: "ApiKey N64VhW8.yChkBUIJeosGojQ7CSR2xwLf3Qy7Apw464",
});
```

Wenn der apiKey individuell zugeteilt ist und nicht öffentlich, sollte dieser in eine extra Datei ausgelagert werden und diese mit entsprechenden Dateiberechtigungen versehen werden.

**Comment by ManAnRuck** [comment]
Hi @ksaadDE
vielen Dank für den Hinweis, ich hab den ApiKey jetzt entfernt und die Readme diesbezüglich erweitert.

**Comment by ksaadDE** [comment]
Das war der schnellste Fix der Welt, sehr erfreulich.  Hatte viel zu tun, konnte es also nicht direkt kommentieren.
Danke Euch! 

Die App an sich (ich weiß, falsches Repo) ist schön.
Mir fällt aber auf, dass besondershäufig Anträge von Linken und Grüne auftauchen.
Liegt das an der Art wie diese arbeiten (Opposition und allgemein populistische Züge im BT) oder liegt das an einer Parteilichkeit eurerseits? (Ich denke, letzteres liegt nicht vor, weil ich den Eindruck habe, dass ihr ein demokratisches Interesse verfolgt)
AfD mal ausgeklammert (aber auch die kommt schon echt häufig in der App vor)
Regierungsparteien sind ja meist eher still und bearbeiten nur die Anträge der Opposition (was eig. auch verkehrte Welt ist... )
Anmk: Ich rede über die Dokumente aus dem BT System (ist das DIP?).

**Comment by ManAnRuck** [comment]
Sehr gerne :) wollte mal OpenApi ausprobieren und schauen wie fix man damit bestehende/undokumentierte RestApis typensicher bekommt und bin selbst begeistert xD

Ich muss gestehen, das mich das auch schon länger interessiert, ich jedoch noch nicht dazu gekommen bin das zu prüfen… Bis jetzt 😅

```mongo
[{
    $match: {
        period: 19
    }
}, {
    $unwind: {
        path: "$initiative"
    }
}, {
    $group: {
        _id: "$initiative",
        count: {
            $sum: 1
        }
    }
}, {
    $sort: {
        count: -1
    }
}]
```

Das wären jetzt die Anzahl der Prozeduren an denen die Initiatoren beteiligt sind (können auch mehrere sein)…
Ist ggf. nicht ganz vollständig jedoch verschafft es schonmal einen kleinen überblick in welche Richtung es geht.

```
_id:"Fraktion der FDP"
count:857
_id:"Fraktion der AfD"
count:687
_id:"Fraktion BÜNDNIS 90/DIE GRÜNEN"
count:664
_id:"Fraktion DIE LINKE"
count:615
_id:"Bundesregierung"
count:537
_id:"Fraktion der SPD"
count:230
_id:"Fraktion der CDU/CSU"
count:224
_id:"Nordrhein-Westfalen"
count:47
_id:"Niedersachsen"
count:26
_id:"Hamburg"
count:24
_id:"Bremen"
count:23
_id:"Berlin"
count:22
_id:"Hessen"
count:20
_id:"Bayern"
count:20
_id:"Thüringen"
count:19
_id:"Rheinland-Pfalz"
count:18
_id:"Brandenburg"
count:16
_id:"Schleswig-Holstein"
count:15
_id:"Baden-Württemberg"
count:12
_id:"Sachsen"
count:12
```

Parteilichkeit unsererseits darf ich glücklicherweise ausschließen, da wir sämtliche `Anträge` und `Gesetzgebungen` 1:1 aus dem DIP (Anmk: ja genau dip 👍🏼) beziehen und an die App durchreichen. Das einzige was wir Redaktionell machen, sind die nicht namentlichen Abstimmungen aus dem Plenarprotokoll auslesen und bestmöglich nachtragen.

**Comment by ksaadDE** [comment]
Dann habe ich Dich ja gut daran erinnert :-D
Hoch spannend! Danke Dir ! 

Die FDP hat mehr Papierkram erzeugt als die Bundesregierung (in der Hinsicht) lol 
Das wird die neue Verschwörungstheorie:  FDP regiert insgeheim, trotz der parlamentarischen Größe, Deutschland xD

Ist das für diese Legis oder für alle?

Bin froh, dass ihr nicht parteilich seid ;) Hätte mich auch gewundert.
Ggf. muss man bei der Sortierung irgendwie darauf achten, dass nicht nur die "aktuellen", sondern auch ein guter Mix bei den Parteien entsteht, auch wenn natürlich einige der Oppositionsparteien glücklicherweise viel Fragen und Beantragen/Einreichen, sollte ein gewisser Ausgleich oder eine Sortierung bestehen.
