### ISSUE TITLE
Align different versions of swagger ui

### ISSUE THREAD

**Issue by hejjoe** [demokratie-live/bt-dip-sdk#7]
There might be some differences between these versions?

https://app.swaggerhub.com/apis-docs/DEMOCRACY/BundestagDIP/0.1

https://search.dip.bundestag.de/api/v1/swagger-ui/

**Comment by hejjoe** [comment]
Looks like this could be fixed by https://github.com/demokratie-live/bt-dip-sdk/pull/8

**Comment by ManAnRuck** [comment]
yes it's fixed now :) 
Thank you :)
